name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    env:
      SHELL: /bin/sh
    steps:          
      - name: Clone mozillabuild
        run: |
          curl https://cdn.dothq.co/artifacts/tools/mozilla-build.zip -o mozilla-build.zip
          ls
          7z x mozilla-build.zip -aoa -oC:\mozilla-build 
        
      - name: Clone mozilla-central
        shell: bash
        run: hg clone https://hg.mozilla.org/mozilla-central

      - name: Bootstrap
        shell: cmd
        run: |
          type nul > C:\script
          echo cd /d/a/windows-artifacts/windows-artifacts/mozilla-central >> C:\script
          echo ls >> C:\script
          echo ./mach bootstrap --application-choice browser >> C:\script
          C:\mozilla-build\start-shell.bat "C:\script"
          
      - name: Check if .mozbuild exists
        uses: dothq/file-or-directory-exists@latest
        with:
          input: |
            $HOME/.mozbuild
          
      - name: Compress mozbuild
        shell: bash
        run: |
          cd ~
          tar --strip-components=1 -cjvf mozbuild.tar.bz2 .mozbuild
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        with:
          tag_name: "#${{ github.run_number }}"
          release_name: "Windows Artifact - #${{ github.run_number }}"
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: C:\Users\runneradmin\mozbuild.tar.bz2
          asset_name: mozbuild.tar.bz2
          asset_content_type: application/x-bzip-compressed-tar
