name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019
    env:
      SHELL: /bin/sh
      MOZ_WINDOWS_BOOTSTRAP: 1 
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            python
            
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /d/a/windows-artifacts/windows-artifacts/mozilla-central
          key: ${{ runner.os }}
          
      - name: Clone mozillabuild
        run: |
          curl https://cdn.dothq.co/artifacts/tools/mozilla-build.zip -o mozilla-build.zip
          ls
          7z x mozilla-build.zip -aoa -oC:\mozilla-build 
        
      - name: Clone mozilla-central
        shell: bash
        run: hg clone https://hg.mozilla.org/mozilla-central

      - name: Bootstrap
        shell: cmd
        run: |
          type nul > C:\script
          echo cd /d/a/windows-artifacts/windows-artifacts/mozilla-central >> C:\script
          echo ls >> C:\script
          echo ./mach bootstrap --application-choice browser --no-interactive >> C:\script
          C:\mozilla-build\start-shell.bat "C:\script"
          
      - name: Compress mozbuild
        shell: bash
        run: |
          cd ~
          tar -cf mozbuild.tar .mozbuild
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Windows Artifact - ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /c/Users/runneradmin/mozbuild.tar
          asset_name: mozbuild.tar
          asset_content_type: application/x-tar
